receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
  newrelicapm:

exporters:
  logging:
    loglevel: debug
  file:
    path: /tmp/wat.json
    format: json
  otlp:
    endpoint: staging-otlp.nr-data.net:4317
    headers:
      api-key: $API_KEY

connectors:
  newrelicapm:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [newrelicapm, batch]
      exporters: [newrelicapm, otlp]
    metrics/out:
      receivers: [newrelicapm]
      processors: [batch]
      exporters: [file, otlp]
    logs/out:
      receivers: [newrelicapm]
      processors: [batch]
      exporters: [otlp]
