receivers:
  nrinfra:

processors:
  batch:
  resource:
    attributes:
      - action: upsert
        key: host.name
        value: wat

exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: staging-otlp.nr-data.net:4317
    headers:
      api-key: $API_KEY
  file:
    path: /tmp/wat.json
    format: json
  nrinfra:
    license_key: $API_KEY

service:
  pipelines:
    metrics:
      receivers: [nrinfra]
      processors: [batch]
      exporters: [nrinfra, logging, file]
